# Generated by Django 3.1.2 on 2020-10-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('unique_squirrel_id', models.CharField(max_length=200)),
                ('shift', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=200, null=True)),
                ('primary_fur_color', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('specific_location', models.CharField(blank=True, max_length=200, null=True)),
                ('other_activities', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
