# Generated by Django 3.1.2 on 2020-10-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20201021_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='latitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='longitude',
            field=models.CharField(max_length=100),
        ),
    ]
