# Generated by Django 3.1.2 on 2020-10-21 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20201021_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='indifferent',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='run_from',
        ),
    ]
