# Generated by Django 3.1.2 on 2020-10-21 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20201021_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='approaches',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='chasing',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='climbing',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='eating',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='foraging',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='kuks',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='moans',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='quaas',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='running',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='tail_flags',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='tail_twitches',
        ),
    ]
