# Generated by Django 3.1.2 on 2020-10-17 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel_sightings',
            old_name='latitude',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='squirrel_sightings',
            old_name='longitude',
            new_name='y',
        ),
        migrations.RemoveField(
            model_name='squirrel_sightings',
            name='data',
        ),
    ]
