# Generated by Django 3.1.2 on 2020-10-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel_tracker', '0002_auto_20201017_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel_sightings',
            old_name='y',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='squirrel_sightings',
            old_name='x',
            new_name='longitude',
        ),
    ]
