# Generated by Django 3.1.2 on 2020-10-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel_tracker', '0003_auto_20201017_1539'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='squirrel_sightings',
            new_name='sightings',
        ),
    ]
