# Generated by Django 3.1.2 on 2020-10-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel_tracker', '0004_auto_20201017_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightings',
            name='latitude',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='longitude',
            field=models.FloatField(max_length=100),
        ),
    ]
