# Generated by Django 3.1.2 on 2020-10-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='approaches',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='chasing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='climbing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='eating',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='foraging',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='indifferent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='kuks',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='moans',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='other_activities',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='primary_fur_color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='quaas',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='run_from',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='running',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='specific_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='tail_flags',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='tail_twitches',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='age',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='shift',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
